### ISSUE TITLE
Add support for basic arithmetic operators

### ISSUE THREAD

**Issue by chros73** [chros73/rtorrent#14]
**I. Summary**
Add support for basic arithmetic operators (`+`, `-`, `*`, `/`, `%`) and `min`, `max`, `count`, `avg`, `median` functions.
All commands:
- support multiple arguments
- support list type as well
- restricted to integer arithmetic (as in `bash`), even `/`
  - rtorrent (and libtorrent) currently handles only integer variables
  - `/`, `avg`, `median` always round down

**II. New commands in rtorrent**
- `math.add`
- `math.sub`
- `math.mul`
- `math.div`
- `math.mod`
- `math.min`
- `math.max`
- `math.cnt`
- `math.avg`
- `math.med`

**III. Arithmetic operators in action** 
```ini
# Subtract 3 numbers: -4
print=(math.sub,5,2,7)
# Divide 3 numbers: 2 !
print=(math.div,80,9,4)

# Calculate size of a download using its size of files (example using list type)
print=(math.add,(f.multicall,,f.size_bytes=))

# Get average size in Bytes of downloads in main view
print=(math.div,(math.add,(d.multicall2,main,d.size_bytes=)),(view.size,main))
```

`math.min` and `math.max` can be used as variable assignment based on intervals as well:
```ini
# Assign 0 if value smaller than 0, or assign value otherwise ( x >= 0 ? x : 0 )
print=(math.max,0,(math.sub,2,7))
# Assign 0 if value smaller than 0, 100 if value is bigger than 100, or assign value otherwise ( x < 0 ? 0 : (x > 100 ? 100 : x) )
print=(math.max,0,(math.min,100,(math.div,500,2)))
```

**Comment by chros73** [comment]
Fix bugs in `math.*` commands (thx to @pyroscope):
- `math.div`/`mod`: fix division by zero
- `math.avg`/`med`: fix invalid char pointer comparison

**Comment by pyroscope** [comment]
https://rtorrent-docs.readthedocs.io/en/latest/cmd-ref.html#math-functions

**Comment by chros73** [comment]
> and maybe 2032 or so in rTorrent.

:D :D :D

**Comment by chros73** [comment]
Merged.
